/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Classes.Consulta;
import Classes.Paciente;
import Classes.Servico;
import Classes.Usuario;
import Dao.ServicoDao;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author augusto
 */
public class EditarConsulta extends javax.swing.JFrame {
    int codigo;
    DefaultListModel model;
    List<Paciente> results;
    int linha;
    List<Servico> servicos;
    List<Servico> servicosP = new ArrayList<>();
    double valorFinalPreco = 0;
    DefaultListModel dlmAdicionar = new DefaultListModel();
    BigDecimal bd;

    /**
     * Creates new form EditarConsulta
     */
    public EditarConsulta(int cod) {
        initComponents();
        codigo = cod;
        iniciar(cod);
        carregar();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpConsulta = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFone = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAnamnese01 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chkAnamnese01 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaAnamnese02 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        chkAnamnese02 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        chkAnamnese03 = new javax.swing.JCheckBox();
        txtMedicacao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAlergia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCirurgia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtHabito = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaObservacoes = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        btnSalvar1 = new javax.swing.JButton();
        btnImprimir1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaExperiencia = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaHigiene = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaTecidos = new javax.swing.JTextArea();
        chkInquerito01 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        btnCancelar2 = new javax.swing.JButton();
        btnSalvar2 = new javax.swing.JButton();
        btnImprimir2 = new javax.swing.JButton();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblOdontograma = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaDescricao = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSalvar3 = new javax.swing.JButton();
        btnImprimir3 = new javax.swing.JButton();
        btnCancelar3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        servicosExistentes = new javax.swing.JList<>();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        servicosPrestados = new javax.swing.JList<>();
        jLabel29 = new javax.swing.JLabel();
        addServico = new javax.swing.JButton();
        removerServico = new javax.swing.JButton();
        desconto = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnSalvar4 = new javax.swing.JButton();
        btnImprimir4 = new javax.swing.JButton();
        btnCancelar4 = new javax.swing.JButton();
        valorFinalw = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        valorFinal = new javax.swing.JLabel();
        usuariologado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtpConsulta.setName(""); // NOI18N
        jtpConsulta.setPreferredSize(new java.awt.Dimension(857, 489));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 732, -1));

        jLabel2.setText("Endereço:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 732, -1));

        jLabel3.setText("RG:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel1.add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 295, -1));

        jLabel4.setText("Orgão emissor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));
        jPanel1.add(txtOe, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 209, -1));

        jLabel5.setText("CPF:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 358, -1));

        jLabel6.setText("Fone:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));
        jPanel1.add(txtFone, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 209, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, -1, -1));

        btnImprimir.setText("Imprimir");
        jPanel1.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, -1, -1));

        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, -1));

        jtpConsulta.addTab("Ficha clínica", jPanel1);

        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 489));

        jLabel7.setText("Queixa principal e evolução da doença atual");

        txaAnamnese01.setColumns(20);
        txaAnamnese01.setRows(5);
        jScrollPane1.setViewportView(txaAnamnese01);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Questionário de saúde");

        jLabel9.setText("Sofre de alguma doença?");

        chkAnamnese01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAnamnese01ActionPerformed(evt);
            }
        });

        jLabel10.setText("Quais?");

        txaAnamnese02.setColumns(20);
        txaAnamnese02.setRows(5);
        jScrollPane2.setViewportView(txaAnamnese02);

        jLabel11.setText("Está em tratamento médico atualmente?");

        jLabel12.setText("Gravidez");

        chkAnamnese03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAnamnese03ActionPerformed(evt);
            }
        });

        jLabel14.setText("Uso de medicação:");

        jLabel15.setText("Alergias:");

        txtAlergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergiaActionPerformed(evt);
            }
        });

        jLabel16.setText("Cirurgias:");

        jLabel17.setText("Hábitos");

        txtHabito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHabitoActionPerformed(evt);
            }
        });

        txaObservacoes.setColumns(20);
        txaObservacoes.setRows(5);
        jScrollPane3.setViewportView(txaObservacoes);

        jLabel13.setText("Observações:");

        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        btnImprimir1.setText("Imprimir");

        btnCancelar1.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(chkAnamnese01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkAnamnese02)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkAnamnese03))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(338, 338, 338)
                                        .addComponent(jLabel8)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMedicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCirurgia)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtHabito)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(328, 328, 328)
                                        .addComponent(jLabel16))
                                    .addComponent(txtAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(365, 365, 365)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar1)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir1)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(chkAnamnese01)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(chkAnamnese02)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(chkAnamnese03))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHabito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar1)
                    .addComponent(btnImprimir1)
                    .addComponent(btnCancelar1))
                .addContainerGap())
        );

        jtpConsulta.addTab("Anamnese", jPanel2);

        jLabel18.setText("Data do último atendimento:");

        jLabel19.setText("Experiência negativa no tratamento anterior:");

        txaExperiencia.setColumns(20);
        txaExperiencia.setRows(5);
        jScrollPane4.setViewportView(txaExperiencia);

        jLabel20.setText("Higiene bucal (utiliza):");

        txaHigiene.setColumns(20);
        txaHigiene.setRows(5);
        jScrollPane5.setViewportView(txaHigiene);

        jLabel21.setText("Tecidos moles:");

        txaTecidos.setColumns(20);
        txaTecidos.setRows(5);
        jScrollPane6.setViewportView(txaTecidos);

        chkInquerito01.setName("chkInquerito01"); // NOI18N
        chkInquerito01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkInquerito01ActionPerformed(evt);
            }
        });

        jLabel22.setText("Ingere alimentos/bebidas entre as refeições?");

        btnCancelar2.setText("Cancelar");

        btnSalvar2.setText("Salvar");
        btnSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar2ActionPerformed(evt);
            }
        });

        btnImprimir2.setText("Imprimir");

        jLabel26.setText("/");

        jLabel27.setText("/");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar2)
                        .addGap(18, 18, 18)
                        .addComponent(btnImprimir2)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(chkInquerito01))
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 547, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(31, 31, 31)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkInquerito01)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar2)
                    .addComponent(btnImprimir2)
                    .addComponent(btnCancelar2))
                .addContainerGap())
        );

        jtpConsulta.addTab("Inquérito odontológico", jPanel3);

        jLabel23.setText("Exame dental: descrição dente a dente");

        txaDescricao.setColumns(20);
        txaDescricao.setRows(5);
        jScrollPane7.setViewportView(txaDescricao);

        jLabel24.setText("Planos de tratamento");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane8.setViewportView(jTextArea1);

        btnSalvar3.setText("Salvar");
        btnSalvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar3ActionPerformed(evt);
            }
        });

        btnImprimir3.setText("Imprimir");

        btnCancelar3.setText("Cancelar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblOdontograma)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(0, 606, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane7)
                                .addContainerGap())))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane8)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar3)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir3)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7))
                    .addComponent(lblOdontograma))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar3)
                    .addComponent(btnImprimir3)
                    .addComponent(btnCancelar3))
                .addContainerGap())
        );

        jtpConsulta.addTab("Odontograma", jPanel4);

        servicosExistentes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane9.setViewportView(servicosExistentes);

        jLabel28.setText("Serviços");

        jScrollPane10.setViewportView(servicosPrestados);

        jLabel29.setText("Serviços Prestados");

        addServico.setText("Add >>");
        addServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addServicoActionPerformed(evt);
            }
        });

        removerServico.setText("<<Remover");
        removerServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerServicoActionPerformed(evt);
            }
        });

        desconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descontoKeyReleased(evt);
            }
        });

        jLabel30.setText("Desconto");

        jLabel31.setText("Valor Final");

        btnSalvar4.setText("Salvar");
        btnSalvar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar4ActionPerformed(evt);
            }
        });

        btnImprimir4.setText("Imprimir");

        btnCancelar4.setText("Cancelar");

        valorFinalw.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        valorFinalw.setText("R$");

        jLabel32.setText("%");

        valorFinal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        valorFinal.setText("0,00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removerServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnSalvar4)
                        .addGap(18, 18, 18)
                        .addComponent(btnImprimir4)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar4)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(valorFinalw)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorFinal))
                            .addComponent(jLabel31)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(desconto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)))
                        .addGap(24, 24, 24))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(addServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removerServico))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                .addGap(38, 38, 38)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(38, 38, 38)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorFinalw)
                    .addComponent(valorFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar4)
                    .addComponent(btnImprimir4)
                    .addComponent(btnCancelar4))
                .addContainerGap())
        );

        jtpConsulta.addTab("Serviços", jPanel6);

        usuariologado.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(usuariologado)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuariologado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jtpConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar(int cod) {
        SessionFactory sf = Util.NewHibernateUtil.getSessionFactory();
        Session s = sf.openSession();
        Transaction tx = s.beginTransaction();

        Criteria criteria = s.createCriteria(Consulta.class);
        criteria.add(Restrictions.eq("cod", cod));
        List<Consulta> consultasLista = criteria.list();
        Consulta consultaRef = consultasLista.get(0);
        
        txtNome.setText(consultaRef.getPaciente().getNome());
        txtEndereco.setText(consultaRef.getPaciente().getEndereco());
        txtRg.setText(consultaRef.getPaciente().getRg());
        txtOe.setText(consultaRef.getPaciente().getOrgaoEmissor());
        txtCpf.setText(consultaRef.getPaciente().getCpf());
        txtFone.setText(consultaRef.getPaciente().getFone());
        txaAnamnese01.setText(consultaRef.getQueixa());
        txaAnamnese02.setText(consultaRef.getDoencaDesc());
        txtMedicacao.setText(consultaRef.getMedicacao());
        txtCirurgia.setText(consultaRef.getCirurgias());
        txtAlergia.setText(consultaRef.getAlergias());
        txtHabito.setText(consultaRef.getHabitos());
        txaObservacoes.setText(consultaRef.getObs());
        txaExperiencia.setText(consultaRef.getXpNegAtendAnterior());
        txaHigiene.setText(consultaRef.getUsaHigieneBucal());
        txaTecidos.setText(consultaRef.getTecidosMoles());
        txaDescricao.setText(consultaRef.getExameDental());
        jTextArea1.setText(consultaRef.getPlanosTratamento() );
        dia.setText(Integer.toString(consultaRef.getDataDaConsulta().getDayOfMonth()));
        mes.setText(Integer.toString(consultaRef.getDataDaConsulta().getMonthValue()));
        ano.setText(Integer.toString(consultaRef.getDataDaConsulta().getYear()));
        servicosP = consultaRef.getServicos();
        for (Servico s1 : servicosP) {
            dlmAdicionar.addElement(s1.getNome());
        }
        valorFinal.setText(Double.toString(consultaRef.getValor()));
        servicosPrestados.setModel(dlmAdicionar);
        txtNome.setEditable(false);
        txtEndereco.setEditable(false);
        txtRg.setEditable(false);
        txtOe.setEditable(false);
        txtCpf.setEditable(false);
        txtFone.setEditable(false);
        
        
        
        

    }
    private void carregar() {
        DefaultListModel modelS = new DefaultListModel();
        servicosExistentes.setModel(modelS);
        servicos = new ServicoDao().retornaTodosOsServicos();
        for (Servico servico : servicos) {
            modelS.addElement(servico.getNome() + " - R$: " + servico.getPreco());
        }
        
        

    }

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased

    }//GEN-LAST:event_txtNomeKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        SessionFactory sf = Util.NewHibernateUtil.getSessionFactory();
        Session s = sf.openSession();
        Transaction tx = s.beginTransaction();

        //vou no banco pego um usuario igual
        Criteria criteria = s.createCriteria(Consulta.class);
        criteria.add(Restrictions.eq("cod", codigo));
        List<Consulta> use = criteria.list();
        
        
        Consulta consulta = Consulta.devolveObjConsulta();
        consulta.setCod(codigo);
        consulta.setPaciente(use.get(0).getPaciente());
        consulta.setDentista(use.get(0).getDentista());
        consulta.setQueixa(txaAnamnese01.getText());
        consulta.setDoenca(chkAnamnese01.isSelected());
        consulta.setDoencaDesc(txaAnamnese02.getText());
        consulta.setTratamento(chkAnamnese02.isSelected());
        consulta.setGravidez(chkAnamnese03.isSelected());
        consulta.setMedicacao(txtMedicacao.getText());
        consulta.setCirurgias(txtCirurgia.getText());
        consulta.setAlergias(txtAlergia.getText());
        consulta.setHabitos(txtHabito.getText());
        consulta.setObs(txaObservacoes.getText());

       
        LocalDate dataAnterior = LocalDate.of(Integer.parseInt(ano.getText()), Integer.parseInt(mes.getText()), Integer.parseInt(dia.getText()));
       
        consulta.setDataDoUltAtendimento(dataAnterior);
        consulta.setDataDaConsulta(LocalDate.now());
        System.out.println(LocalDate.now());
        consulta.setXpNegAtendAnterior(txaExperiencia.getText());
        consulta.setUsaHigieneBucal(txaHigiene.getText());
        consulta.setTecidosMoles(txaTecidos.getText());
        consulta.setIngeriAlimentosbebidasRefeicoes(chkInquerito01.isSelected());
        consulta.setExameDental(txaDescricao.getText());
        consulta.setPlanosTratamento(jTextArea1.getText());
        consulta.setServicos(servicosP);
        consulta.setValor(Double.parseDouble(valorFinal.getText()));
        consulta.setDesconto(Integer.parseInt(desconto.getText()));
        s.merge(consulta);
        tx.commit();
        s.close();
        JOptionPane.showMessageDialog(null, "Consulta Atualizada");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void chkAnamnese01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAnamnese01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAnamnese01ActionPerformed

    private void chkAnamnese03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAnamnese03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAnamnese03ActionPerformed

    private void txtAlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergiaActionPerformed

    private void txtHabitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHabitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHabitoActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        btnSalvarActionPerformed(evt);
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void chkInquerito01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkInquerito01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkInquerito01ActionPerformed

    private void btnSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar2ActionPerformed
        btnSalvarActionPerformed(evt);
    }//GEN-LAST:event_btnSalvar2ActionPerformed

    private void btnSalvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar3ActionPerformed
        btnSalvarActionPerformed(evt);
    }//GEN-LAST:event_btnSalvar3ActionPerformed

    private void addServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServicoActionPerformed
        dlmAdicionar.removeAllElements();
        valorFinalPreco = 0;
        int in = servicosExistentes.getSelectedIndex();

        for (Servico sw : servicos) {
            if (servicosExistentes.getSelectedValue().contains(sw.getNome())) {
                servicosP.add(sw);

            }
        }
        for (Servico s : servicosP) {
            dlmAdicionar.addElement(s.getNome());

            valorFinalPreco += s.getPreco();
        }
        servicosPrestados.setModel(dlmAdicionar);

        bd = new BigDecimal(valorFinalPreco).setScale(3, RoundingMode.HALF_EVEN);
        valorFinal.setText(Double.toString(bd.doubleValue()));

    }//GEN-LAST:event_addServicoActionPerformed

    private void removerServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerServicoActionPerformed
        try {
            if (valorFinalPreco == 0) {
                throw new Exception();
            }
            valorFinalPreco = 0;
            int count = 0;
            for (Iterator<Servico> i = servicosP.iterator(); i.hasNext();) {
                Servico s = i.next();

                if (s.getNome() == servicosPrestados.getSelectedValue() && count == 0) {
                    i.remove();
                    count++;

                }
            }

            //if(servicosPrestados.getSelectedValue())
            /*
            for (Servico s : servicosP) {
                int count = 0;

                if (s.getNome() == servicosPrestados.getSelectedValue() && count == 0) {
                    System.out.println("cond1 ___ " + s.getNome() + " cond2_________" + servicosPrestados.getSelectedValue());
                    servicosP.remove(s);
                    count++;

                }
            }
            */
            dlmAdicionar.removeAllElements();
            for (Servico s : servicosP) {
                dlmAdicionar.addElement(s.getNome());
                valorFinalPreco += s.getPreco();
            }

            bd = new BigDecimal(valorFinalPreco).setScale(3, RoundingMode.HALF_EVEN);
            valorFinal.setText(Double.toString(bd.doubleValue()));
            servicosPrestados.setModel(dlmAdicionar);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Selecione um item para retirar");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_removerServicoActionPerformed

    private void descontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descontoKeyReleased
        double vfp = Double.parseDouble(valorFinal.getText()) - Double.parseDouble(valorFinal.getText()) * (Double.parseDouble(desconto.getText()) / 100);
        valorFinal.setText(Double.toString(vfp));
    }//GEN-LAST:event_descontoKeyReleased

    private void btnSalvar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar4ActionPerformed
        btnSalvarActionPerformed(evt);
    }//GEN-LAST:event_btnSalvar4ActionPerformed

    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarConsulta().setVisible(true);
            }
        });
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addServico;
    private javax.swing.JTextField ano;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnCancelar3;
    private javax.swing.JButton btnCancelar4;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnImprimir2;
    private javax.swing.JButton btnImprimir3;
    private javax.swing.JButton btnImprimir4;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnSalvar2;
    private javax.swing.JButton btnSalvar3;
    private javax.swing.JButton btnSalvar4;
    private javax.swing.JCheckBox chkAnamnese01;
    private javax.swing.JCheckBox chkAnamnese02;
    private javax.swing.JCheckBox chkAnamnese03;
    private javax.swing.JCheckBox chkInquerito01;
    private javax.swing.JTextField desconto;
    private javax.swing.JTextField dia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTabbedPane jtpConsulta;
    private javax.swing.JLabel lblOdontograma;
    private javax.swing.JTextField mes;
    private javax.swing.JButton removerServico;
    private javax.swing.JList<String> servicosExistentes;
    private javax.swing.JList<String> servicosPrestados;
    private javax.swing.JTextArea txaAnamnese01;
    private javax.swing.JTextArea txaAnamnese02;
    private javax.swing.JTextArea txaDescricao;
    private javax.swing.JTextArea txaExperiencia;
    private javax.swing.JTextArea txaHigiene;
    private javax.swing.JTextArea txaObservacoes;
    private javax.swing.JTextArea txaTecidos;
    private javax.swing.JTextField txtAlergia;
    private javax.swing.JTextField txtCirurgia;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFone;
    private javax.swing.JTextField txtHabito;
    private javax.swing.JTextField txtMedicacao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtOe;
    private javax.swing.JTextField txtRg;
    private javax.swing.JLabel usuariologado;
    private javax.swing.JLabel valorFinal;
    private javax.swing.JLabel valorFinalw;
    // End of variables declaration//GEN-END:variables
}
