/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Util.Banco;
import Classes.Paciente;
import Classes.Usuario;
import Dao.PacienteDao;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.objects.NativeArray;
import org.hibernate.*;

/**
 *
 * @author augusto
 */
public class ListarPacientes extends javax.swing.JFrame {
    int clique = 0;
    /**
     * Creates new form ListarPacientes
     */
    public ListarPacientes() throws Exception {
        initComponents();
        carregar();
        usuariologado.setText(TelaDeLogin.usuario);
        setSize(1280, 720);
        this.setLocationRelativeTo(null);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Editar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        usuariologado = new javax.swing.JLabel();
        listarConsultas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Pacientes");

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Tipo", "Título 4", "Título 5", "Título 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        usuariologado.setText("Usuario");

        listarConsultas.setText("Listar Consultas");
        listarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(listarConsultas)
                        .addGap(18, 18, 18)
                        .addComponent(Editar)
                        .addGap(18, 18, 18)
                        .addComponent(Excluir)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usuariologado)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuariologado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Excluir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Editar)
                        .addComponent(listarConsultas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        try {
            Object i = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            int a = Integer.parseInt(i.toString());
            new EditarPaciente(a);
            carregar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um usuário");
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        String usuarioSelecionado = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        Paciente usuario = Paciente.devolveInstanciaDePaciente();
        Object i = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        int a = Integer.parseInt(i.toString());
        usuario.setId(a);
        int botao = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Deseja Realmente apagar " + usuarioSelecionado, "Cuidado", botao);
        if (usuarioSelecionado.equals("admin")) {
            JOptionPane.showMessageDialog(rootPane, "ô seu animal, quer excluir o administrador");
            this.dispose();
        } else {
            if (botao == JOptionPane.YES_OPTION) {
                new PacienteDao().deletar(usuario);

            }
        }
        try {
            carregar();
        } catch (Exception e) {
            //vai dar erro não pvt
        }

    }//GEN-LAST:event_ExcluirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarConsultasActionPerformed
        if(clique == 1){
        int cod = Integer.parseInt((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        new ListarConsultasPorPaciente(cod);
        clique = 0;
        
        }else{
            clique++;
        }
                
        
    }//GEN-LAST:event_listarConsultasActionPerformed

    private void carregar() throws Exception {
         List<Paciente> results; 
        Paciente usuario = Paciente.devolveInstanciaDePaciente();
        SessionFactory sf = Util.NewHibernateUtil.getSessionFactory();
        Session s = sf.openSession();

        Criteria crite = s.createCriteria(Paciente.class);
        
            results = crite.list();
        
         
        List<String[]> lista = new ArrayList<String[]>();

        for (int i = 0; i < results.size(); i++) {

            usuario = results.get(i);

            lista.add(new String[]{"" + usuario.getId() + "", usuario.getNome(),""+usuario.getDataDeNacimento()+"", usuario.getCpf(), usuario.getEndereco(), "" + usuario.getSexo() + ""});
        }

        String[] colunas = {"Id", "Nome", "Nascimento", "CPF", "Endereço", "Sexo"};
        DefaultTableModel model = new DefaultTableModel(lista.toArray(new String[lista.size()][]), colunas);
        jTable1.setModel(model);

        s.close();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listarConsultas;
    private javax.swing.JLabel usuariologado;
    // End of variables declaration//GEN-END:variables
}
