/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Classes.Consulta;
import Classes.Paciente;
import Util.GeradorDePdf;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 *
 * @author augusto
 */
public class ListarConsultas extends javax.swing.JFrame {

    /**
     * Creates new form ListarConsultas
     */
    public ListarConsultas() throws Exception{
        initComponents();
        carregar();
        usuariologado.setText(TelaDeLogin.usuario);
       setSize(1280, 720);
        this.setLocationRelativeTo(null);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarConsulta = new javax.swing.JButton();
        excluirConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        usuariologado = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editarConsulta.setText("Editar");
        editarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarConsultaActionPerformed(evt);
            }
        });

        excluirConsulta.setText("Excluir");
        excluirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirConsultaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Tipo", "Título 4", "Título 5", "Título 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        usuariologado.setText("Usuario");

        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/print.png"))); // NOI18N
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editarConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(excluirConsulta)
                        .addGap(45, 45, 45)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usuariologado)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imprimir)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuariologado)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(excluirConsulta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editarConsulta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarConsultaActionPerformed
        try {
            Object i = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            int a = Integer.parseInt(i.toString());
            new EditarConsulta(a);
            carregar();
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um usuário\n"+e);
        }
    }//GEN-LAST:event_editarConsultaActionPerformed

    private void excluirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirConsultaActionPerformed
        String usuarioSelecionado = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        Consulta usuario = Consulta.devolveObjConsulta();
        Object i = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        int a = Integer.parseInt(i.toString());
        usuario.setId(a);
        int botao = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Deseja Realmente apagar " + usuarioSelecionado, "Cuidado", botao);
        if (usuarioSelecionado.equals("admin")) {
            JOptionPane.showMessageDialog(rootPane, "ô seu animal, quer excluir o administrador");
            this.dispose();
        } else {
            if (botao == JOptionPane.YES_OPTION) {
                System.out.println("DEu simm");
                SessionFactory sf = Util.NewHibernateUtil.getSessionFactory();
                Session s = sf.openSession();
                Transaction tx = s.beginTransaction();
                s.delete(usuario);
                tx.commit();
                s.close();

            }
        }
        try {
            carregar();
        } catch (Exception e) {
            //vai dar erro não pvt
        }
    }//GEN-LAST:event_excluirConsultaActionPerformed
    private void carregar() throws Exception {
         List<Consulta> results; 
        Consulta consulta = Consulta.devolveObjConsulta();
        SessionFactory sf = Util.NewHibernateUtil.getSessionFactory();
        Session s = sf.openSession();

        Criteria crite = s.createCriteria(Consulta.class);
        
            results = crite.list();
        
         
        List<String[]> lista = new ArrayList<String[]>();

        for (int i = 0; i < results.size(); i++) {

            consulta = results.get(i);

            lista.add(new String[]{"" + consulta.getId()+ "", consulta.getPaciente().getNome(),""+consulta.getDataDoUltAtendimento()+ ""});
        }

        String[] colunas = {"Id", "Nome do Paciente", "Data"};
        DefaultTableModel model = new DefaultTableModel(lista.toArray(new String[lista.size()][]), colunas);
        jTable1.setModel(model);

        s.close();
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
         Object i = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
         int a = Integer.parseInt(i.toString());
         try{   
         new GeradorDePdf().gerar(a);
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Selecione uma Consulta\n"+e);
         }
    }//GEN-LAST:event_imprimirActionPerformed

    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarConsultas().setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarConsulta;
    private javax.swing.JButton excluirConsulta;
    private javax.swing.JButton imprimir;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel usuariologado;
    // End of variables declaration//GEN-END:variables
}
